### ISSUE TITLE
Testimonials Section

### ISSUE THREAD

**Issue by DeAngelo777** [DeAngelo777/Collab-svetaine#1]
![Screenshot from 2024-08-09 13-46-55](https://github.com/user-attachments/assets/2dc872ce-6f99-4ed7-93bf-0ef3a20ca918)

Padaryti Section

**Comment by DeAngelo777** [comment]
Nuotraukos:
![Group 8](https://github.com/user-attachments/assets/6866020e-e7be-46ae-acb0-cc7a51618062)
![Ellipse 24](https://github.com/user-attachments/assets/5de72934-e6d0-4c99-a22d-f4c4f285cffc)
![Screenshot from 2024-08-09 13-49-48](https://github.com/user-attachments/assets/d2f7165a-3667-476b-b460-b18dddf79a69)
![Screenshot from 2024-08-09 13-50-30](https://github.com/user-attachments/assets/0117c192-d0ed-414a-ba6d-1e8e3a900d7d)

Background color #fcf8fe

**Comment by Lusalvis** [comment]
done?

**Comment by DeAngelo777** [comment]
Tai manau dabar gerai kaip ir bus, dar prieš miegą po 1 commit isaut it
užteks

**Comment by DeAngelo777** [comment]
Čia dar gerai padarėme prieš kitus palyginti, bet dabar suprantu kodėl
individualios svetainės nuo 1k eina :D
